# Generated by Django 4.1.5 on 2023-01-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crawler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=20, verbose_name="MODE")),
                ("keyword", models.TextField(verbose_name="KEYWORD")),
                (
                    "state",
                    models.CharField(
                        default="initialized", max_length=20, verbose_name="STATE"
                    ),
                ),
                (
                    "total_image",
                    models.IntegerField(default=0, verbose_name="TOTAL IMAGE"),
                ),
                (
                    "collected_image",
                    models.IntegerField(default=0, verbose_name="COLLECTED IMAGE"),
                ),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DT"),
                ),
                ("website", models.TextField(verbose_name="WEBSITE")),
                ("pid", models.IntegerField(default=-1, verbose_name="PID")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, unique=True, verbose_name="NAME"),
                ),
                ("mode", models.CharField(max_length=20, verbose_name="MODE")),
                ("keyword", models.TextField(verbose_name="KEYWORD")),
                (
                    "state",
                    models.CharField(
                        default="initialized", max_length=20, verbose_name="STATE"
                    ),
                ),
                (
                    "total_image",
                    models.IntegerField(default=0, verbose_name="TOTAL IMAGE"),
                ),
                (
                    "collected_image",
                    models.IntegerField(default=0, verbose_name="COLLECTED IMAGE"),
                ),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DT"),
                ),
            ],
            options={"ordering": ("create_dt",),},
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(verbose_name="URL")),
                ("save_path", models.TextField(default="/", verbose_name="SAVE PATH")),
                (
                    "cut",
                    models.CharField(blank=True, max_length=20, verbose_name="CUT"),
                ),
                (
                    "part",
                    models.CharField(blank=True, max_length=20, verbose_name="PART"),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="DIRECTION"
                    ),
                ),
                (
                    "pose",
                    models.CharField(blank=True, max_length=20, verbose_name="POSE"),
                ),
                (
                    "is_head",
                    models.CharField(blank=True, max_length=20, verbose_name="IS HEAD"),
                ),
                (
                    "person_count",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="PERSON COUNT"
                    ),
                ),
                (
                    "crawler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="crawler.crawler",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="crawler.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crawler",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="crawler.project"
            ),
        ),
    ]
